name: xtensor-signal
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - ninja
  # Host dependencies
  - xsimd
  - xtensor=0.24.0
  - xtensor-blas
  - lapack
  - openblas
  - doctest