name: xtensor-signal
channels:
- conda-forge
dependencies:
  # Build dependencies
- cmake
- ninja
  # Host dependencies
- xsimd
- xtensor=0.24.6
- xtensor-io
- xtensor-blas
- lapack
- openblas
- doctest
- zlib
- pre-commit
